### PR TITLE
Android viewfindersettings

### PR DESCRIPTION
**Pull request by ruslo**
Apply backport of this patch: https://codereview.qt-project.org/#/c/150849/
Fix for issue #109

### CODE REVIEW

**Comment by ruslo** [comment]
@headupinclouds Note: do not forget to pull new changes from Hunter. Also we can use non-patched CMake 3.5+ for iOS projects.

**Comment by ruslo** [comment]
> Also we can use non-patched CMake 3.5+ for iOS projects

3.5 available from brew: `brew unlink cmake`, `brew update`, `brew install cmake`

New `--ios-combined` and `--ios-multiarch` added to Polly. See notes:
- https://github.com/ruslo/polly/wiki/Toolchain-list#ios

**Comment by headupinclouds** [comment]
Awesome.  I'll give it a try on my device soon.

Also, I'll check out CMake 3.5 this weekend.  That looks really nice.  BTW, I have a # of scripts that rely on the current polly `build.py --framework` option.  Can we hang on to this stuff for a while longer?

**Comment by ruslo** [comment]
> I have a # of scripts that rely on the current polly build.py --framework option. Can we hang on to this stuff for a while longer?

Sure. By the way creating dynamic iOS framework ends with signing problems, need to investigate why.

**Pull request merged**
